export const APPOINTMENT_REGISTER_REQUEST = 'APPOINTMENT_REGISTER_REQUEST';
export const APPOINTMENT_REGISTER_SUCCESS = 'APPOINTMENT_REGISTER_SUCCESS';
export const APPOINTMENT_REGISTER_FAIL = 'APPOINTMENT_REGISTER_FAIL';

export const APPOINTMENT_SIGNIN_REQUEST = 'APPOINTMENT_SIGNIN_REQUEST';
export const APPOINTMENT_SIGNIN_SUCCESS = 'APPOINTMENT_SIGNIN_SUCCESS';
export const APPOINTMENT_SIGNIN_FAIL = 'APPOINTMENT_SIGNIN_FAIL';

export const APPOINTMENT_SIGNOUT = 'APPOINTMENT_SIGNOUT';

export const APPOINTMENT_DETAILS_REQUEST = 'APPOINTMENT_DETAILS_REQUEST';
export const APPOINTMENT_DETAILS_SUCCESS = 'APPOINTMENT_DETAILS_SUCCESS';
export const APPOINTMENT_DETAILS_FAIL = 'APPOINTMENT_DETAILS_FAIL';
export const APPOINTMENT_DETAILS_RESET = 'APPOINTMENT_DETAILS_RESET';

export const APPOINTMENT_LIST_REQUEST = 'APPOINTMENT_LIST_REQUEST';
export const APPOINTMENT_LIST_SUCCESS = 'APPOINTMENT_LIST_SUCCESS';
export const APPOINTMENT_LIST_FAIL = 'APPOINTMENT_LIST_FAIL';

export const EXPERT_LIST_REQUEST = 'EXPERT_LIST_REQUEST';
export const EXPERT_LIST_SUCCESS = 'EXPERT_LIST_SUCCESS';
export const EXPERT_LIST_FAIL = 'EXPERT_LIST_FAIL';

export const APPOINTMENT_UPDATE_PROFILE_REQUEST = 'APPOINTMENT_UPDATE_PROFILE_REQUEST';
export const APPOINTMENT_UPDATE_PROFILE_SUCCESS = 'APPOINTMENT_UPDATE_PROFILE_SUCCESS';
export const APPOINTMENT_UPDATE_PROFILE_FAIL = 'APPOINTMENT_UPDATE_PROFILE_FAIL';
export const APPOINTMENT_UPDATE_PROFILE_RESET = 'APPOINTMENT_UPDATE_PROFILE_RESET';

export const APPOINTMENT_UPDATE_REQUEST = 'APPOINTMENT_UPDATE_REQUEST';
export const APPOINTMENT_UPDATE_SUCCESS = 'APPOINTMENT_UPDATE_SUCCESS';
export const APPOINTMENT_UPDATE_FAIL = 'APPOINTMENT_UPDATE_FAIL';
export const APPOINTMENT_UPDATE_RESET = 'APPOINTMENT_UPDATE_RESET';

export const APPOINTMENT_DELETE_REQUEST = 'APPOINTMENT_DELETE_REQUEST';
export const APPOINTMENT_DELETE_SUCCESS = 'APPOINTMENT_DELETE_SUCCESS';
export const APPOINTMENT_DELETE_FAIL = 'APPOINTMENT_DELETE_FAIL';
export const APPOINTMENT_DELETE_RESET = 'APPOINTMENT_DELETE_RESET';

export const APPOINTMENT_ADDRESS_MAP_CONFIRM = 'APPOINTMENT_ADDRESS_MAP_CONFIRM';
