export const WITHDRAWAL_REGISTER_REQUEST = 'WITHDRAWAL_REGISTER_REQUEST';
export const WITHDRAWAL_REGISTER_SUCCESS = 'WITHDRAWAL_REGISTER_SUCCESS';
export const WITHDRAWAL_REGISTER_FAIL = 'WITHDRAWAL_REGISTER_FAIL';

export const WITHDRAWAL_SIGNIN_REQUEST = 'WITHDRAWAL_SIGNIN_REQUEST';
export const WITHDRAWAL_SIGNIN_SUCCESS = 'WITHDRAWAL_SIGNIN_SUCCESS';
export const WITHDRAWAL_SIGNIN_FAIL = 'WITHDRAWAL_SIGNIN_FAIL';

export const WITHDRAWAL_SIGNOUT = 'WITHDRAWAL_SIGNOUT';

export const WITHDRAWAL_DETAILS_REQUEST = 'WITHDRAWAL_DETAILS_REQUEST';
export const WITHDRAWAL_DETAILS_SUCCESS = 'WITHDRAWAL_DETAILS_SUCCESS';
export const WITHDRAWAL_DETAILS_FAIL = 'WITHDRAWAL_DETAILS_FAIL';
export const WITHDRAWAL_DETAILS_RESET = 'WITHDRAWAL_DETAILS_RESET';

export const WITHDRAWAL_LIST_REQUEST = 'WITHDRAWAL_LIST_REQUEST';
export const WITHDRAWAL_LIST_SUCCESS = 'WITHDRAWAL_LIST_SUCCESS';
export const WITHDRAWAL_LIST_FAIL = 'WITHDRAWAL_LIST_FAIL';

export const EXPERT_LIST_REQUEST = 'EXPERT_LIST_REQUEST';
export const EXPERT_LIST_SUCCESS = 'EXPERT_LIST_SUCCESS';
export const EXPERT_LIST_FAIL = 'EXPERT_LIST_FAIL';

export const WITHDRAWAL_UPDATE_PROFILE_REQUEST = 'WITHDRAWAL_UPDATE_PROFILE_REQUEST';
export const WITHDRAWAL_UPDATE_PROFILE_SUCCESS = 'WITHDRAWAL_UPDATE_PROFILE_SUCCESS';
export const WITHDRAWAL_UPDATE_PROFILE_FAIL = 'WITHDRAWAL_UPDATE_PROFILE_FAIL';
export const WITHDRAWAL_UPDATE_PROFILE_RESET = 'WITHDRAWAL_UPDATE_PROFILE_RESET';

export const WITHDRAWAL_UPDATE_REQUEST = 'WITHDRAWAL_UPDATE_REQUEST';
export const WITHDRAWAL_UPDATE_SUCCESS = 'WITHDRAWAL_UPDATE_SUCCESS';
export const WITHDRAWAL_UPDATE_FAIL = 'WITHDRAWAL_UPDATE_FAIL';
export const WITHDRAWAL_UPDATE_RESET = 'WITHDRAWAL_UPDATE_RESET';

export const WITHDRAWAL_DELETE_REQUEST = 'WITHDRAWAL_DELETE_REQUEST';
export const WITHDRAWAL_DELETE_SUCCESS = 'WITHDRAWAL_DELETE_SUCCESS';
export const WITHDRAWAL_DELETE_FAIL = 'WITHDRAWAL_DELETE_FAIL';
export const WITHDRAWAL_DELETE_RESET = 'WITHDRAWAL_DELETE_RESET';

